name: Backend CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read
  
defaults:
  run:
    working-directory: ./backend

jobs:
  lint-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.10' ]

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"
    - run: |
        poetry install
    
    - name: Lint with black
      run: |
        poetry run black --check --verbose .
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      env:
        TEST_MONGO_URI: ${{secrets.TEST_MONGO_URI}}
      run: |
        poetry run pytest --asyncio-mode=strict
